version: '3.8'
services:
  apps:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${MODE}
      - EXP_TIME=${EXP_TIME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - ES_HOST=${ES_HOST}
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch
      - postgres
    networks:
      - dev-networks
    mem_limit: 512m
    cpus: "0.5"

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - dev-networks
    mem_limit: 256m
    cpus: "0.25"    

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - dev-networks
    mem_limit: 512m 
    cpus: "0.5"

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-networks
    mem_limit: 512m
    cpus: "0.5"

  elasticsearch:
    image: elasticsearch:7.17
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - dev-network
    mem_limit: 1g
    cpus: "1.0"
networks:
  dev-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data:
  postgres-data:
  es-data:
