name: Keep App Awake

on:
  schedule:
    - cron: "*/6 * * * *"  
  workflow_dispatch:

jobs:
  curl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your app
        run: curl -s http://shopman.onrender.com/ > /dev/null
